name: Build Windows

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: windows-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
      - uses: ilammy/msvc-dev-cmd@v1
      - run: choco install strawberryperl make --no-progress
      - uses: oven-sh/setup-bun@v2
      - name: Test and build
        shell: pwsh
        run: ./scripts/Build-Windows.ps1 -BuildExecutable
      - uses: actions/upload-artifact@v4
        with:
          name: iloader-windows
          if-no-files-found: error
          path: artifacts/windows/*
